"""Inference: loads artifacts or deterministic rule fallback so app always runs.

SECURITY (S09): model/scaler are Python pickles. Unpickling executes arbitrary code if the
file was tampered with, so:
  1. paths are fixed inside this package's artifacts dir (no user-controlled paths);
  2. files over 100 MB are refused (DoS guard);
  3. `train.py` writes `.sha256` sidecars that are verified here when present;
  4. any verification/load failure falls back to the deterministic rule model.
Only deploy artifacts generated by `python -m backend.ml.train` from trusted data.
"""
import hashlib
import logging
import os, json, math
import numpy as np
from . import explain as _ex  # noqa (keeps package importable)

log = logging.getLogger("retainiq.ml")

ART = os.path.join(os.path.dirname(__file__), "artifacts")
FEATS = ["tenure_months","age","income","avg_balance","balance_trend","txn_freq","avg_txn",
 "txn_trend","card_usage","product_count","has_loan","complaints","resolution_days",
 "logins","engagement_decline","inactivity_days","failed_rate"]

MAX_ARTIFACT_BYTES = 100 * 1024 * 1024

_model = _scaler = None


def _sha256(path: str) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def _verified_path(name: str) -> str:
    # Fixed-dir join only; callers never pass user input here.
    p = os.path.abspath(os.path.join(ART, name))
    if os.path.commonpath([p, os.path.abspath(ART)]) != os.path.abspath(ART):
        raise ValueError(f"Refusing to load artifact outside artifacts dir: {name}")
    if not os.path.exists(p):
        raise FileNotFoundError(name)
    if os.path.getsize(p) > MAX_ARTIFACT_BYTES:
        raise ValueError(f"Artifact too large, refusing to unpickle: {name}")
    sidecar = p + ".sha256"
    if os.path.exists(sidecar):
        try:
            expected = open(sidecar).read().strip().split()[0]
        except Exception:
            expected = ""
        if expected and _sha256(p) != expected:
            raise ValueError(f"Artifact integrity check failed: {name} (regenerate via ml.train)")
    else:
        log.warning("No integrity sidecar for %s — generated by an older train.py; "
                    "retrain to create one", name)
    return p


def _load():
    global _model, _scaler
    import pickle  # nosec B403 -- trusted artifacts only (sha256-verified, fixed paths)
    try:
        with open(_verified_path("model.pkl"), "rb") as f:
            _model = pickle.load(f)  # nosec B301 -- see module docstring (S09)
        with open(_verified_path("scaler.pkl"), "rb") as f:
            _scaler = pickle.load(f)  # nosec B301 -- see module docstring (S09)
        return True
    except Exception as e:
        log.warning("Artifact load failed (%s); using rule fallback", e)
        _model = _scaler = None
        return False


def _rule(feats: dict) -> float:
    z = (-0.05*feats.get("tenure_months", 24)/12 + 0.9*feats.get("complaints", 0)
         - 2.2*feats.get("txn_trend", 0) - 1.8*feats.get("balance_trend", 0)
         + 1.5*feats.get("engagement_decline", 0) + 0.04*feats.get("inactivity_days", 0)
         - 0.5*feats.get("product_count", 1) - 0.06*feats.get("logins", 8)
         + 3.0*feats.get("failed_rate", 0) - 0.8)
    return 1/(1+math.exp(-z))


def predict_proba(feats: dict) -> float:
    if _model is None:
        _load()
    if _model is not None and _scaler is not None:
        try:
            import numpy as np
            v = np.array([[float(feats.get(k, 0)) for k in FEATS]])
            v = _scaler.transform(v)
            p = float(_model.predict_proba(v)[0][1])
            return max(0.01, min(0.99, p))
        except Exception as e:
            log.debug("Model inference failed (%s); using rule fallback", e)
    return round(max(0.01, min(0.99, _rule(feats))), 4)
